type CheckIn @entity(immutable: true) {
  id: Bytes!
  member: Member!
  day: BigInt!
  timestamp: BigInt!
  note: String!
  transactionHash: Bytes!
  blockNumber: BigInt!
  logIndex: BigInt!
}

type Member @entity(immutable: false) {
  id: Bytes!
  totalCheckIns: BigInt!
  streak: BigInt!
  lastCheckInDay: BigInt!
  lastCheckInAt: BigInt!
  checkIns: [CheckIn!]! @derivedFrom(field: "member")
}

type MonthlyMember @entity(immutable: false) {
  id: String!
  month: String!
  member: Bytes!
  checkIns: BigInt!
  lastCheckInAt: BigInt!
}
