type CheckIn @entity(immutable: true) {
  id: Bytes!
  member: Member!
  utcDay: BigInt!
  note: String!
  timestamp: BigInt!
  blockNumber: BigInt!
  transactionHash: Bytes!
  logIndex: BigInt!
}

type Member @entity(immutable: false) {
  id: Bytes!
  totalCheckIns: BigInt!
  currentStreak: BigInt!
  lastCheckInDay: BigInt!
  lastCheckInAt: BigInt!
  checkIns: [CheckIn!]! @derivedFrom(field: "member")
}

type MonthlyMember @entity(immutable: false) {
  id: String!
  month: Int!
  member: Member!
  checkIns: BigInt!
  lastCheckInAt: BigInt!
}
