type CheckIn @entity(immutable: true) {
  id: Bytes!
  member: Member!
  note: String!
  day: BigInt!
  timestamp: BigInt!
  blockNumber: BigInt!
  sequence: BigInt!
  transactionHash: Bytes!
}

type Member @entity {
  id: Bytes!
  totalCheckIns: BigInt!
  indexedStreak: BigInt!
  lastCheckInDay: BigInt!
  lastCheckInAt: BigInt!
  checkIns: [CheckIn!]! @derivedFrom(field: "member")
  months: [MemberMonth!]! @derivedFrom(field: "member")
}

type MemberMonth @entity {
  id: Bytes!
  member: Member!
  month: String!
  count: BigInt!
}
