type CheckIn @entity(immutable: true) {
  id: ID!
  checkInId: BigInt!
  member: Member!
  memberAddress: Bytes!
  day: BigInt!
  note: String!
  streakAfter: BigInt!
  memberTotalAfter: BigInt!
  timestamp: BigInt!
  blockNumber: BigInt!
  transactionHash: Bytes!
  logIndex: BigInt!
  month: Month!
  monthMember: MonthMember!
}

type Member @entity(immutable: false) {
  id: ID!
  address: Bytes!
  currentStreak: BigInt!
  totalCheckIns: BigInt!
  lastCheckInDay: BigInt!
  lastCheckInAt: BigInt!
  checkIns: [CheckIn!]! @derivedFrom(field: "member")
  months: [MonthMember!]! @derivedFrom(field: "member")
}

type Month @entity(immutable: false) {
  id: ID!
  year: Int!
  month: Int!
  totalCheckIns: BigInt!
  checkIns: [CheckIn!]! @derivedFrom(field: "month")
  members: [MonthMember!]! @derivedFrom(field: "month")
}

type MonthMember @entity(immutable: false) {
  id: ID!
  month: Month!
  member: Member!
  memberAddress: Bytes!
  checkIns: BigInt!
  lastCheckInAt: BigInt!
  checkInEvents: [CheckIn!]! @derivedFrom(field: "monthMember")
}
